name: Build and update caches
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    uses: ./.github/workflows/build.yml
    with:
      run-tests: false
      update-caches: true
