
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/cmake-4.0.0-windows-x86_64/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:12 (PROJECT)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
...
